README.rst
result/result.py

I have seen `result` used in Python code where the main differentiation was between "no error" and "error". Since we didn't really care about the return value, the call was
`return Ok(True)`
This was repeated in several places and just looks funny. The actual value of the default setting doesn't even matter, just the fact that there is one would make usability better.

default `Ok` instance values to `True`

---

CHANGELOG.md
README.rst
result/result.py
result/tests.py

Happy to see this module exists.
I was toying with it the other day and felt I could make my code simpler using a bit of chaining.
So here are the [and_then](https://doc.rust-lang.org/std/result/enum.Result.html#method.and_then) and [or_else}(https://doc.rust-lang.org/std/result/enum.Result.html#method.or_else) inspired methods.
I added the kwargs option for more flexibility (and clarity)
I also added the __eq__  magic method as Ok(1) was not equal to Ok(1)

__eq__ magic method

---

README.rst
result/__init__.py
result/result.py
result/tests.py

This PR adds the `unwrap`, `unwrap_or` and `expect` methods to `Result`, as suggested in #3.

Added `unwrap`, `unwrap_or` and `expect`

---

.travis.yml
requirements-dev.txt
setup.py

Only require typing module below Python 3.5.
Fixes #12.

Typing constraints

---

.coveragerc
.travis.yml
CHANGELOG.md
README.rst
requirements-dev.txt
result/result.py
result/typetests.py

 Change order of generic Result types to [T, E] 

---

README.rst

Missed some extra backticks and added an extra space at the end.

README: Fix markup

---

MIGRATING.md

I missed something when writing the migration guide. `isinstance(res, Result)` should be replaced by `isinstance(res, OkErr)`, not by `isinstance(res, Result)` which is the exact same...

Change left over `Result` to `OkErr` in the migrating guide

---

result/result.py
result/tests.py

This PR should merely be regarded as a suggestion and to discuss if this change would be desirable.
Including the result when constructing `UnwrapError` enables using Python's exception semantics in a similar fashion to Rust's `?` early return operator. 
<details open>
<summary>Example usage</summary>
<p>Performing a series of failable operations, while obtaining context about the failed operation upon unwrapping. This is different from using regular exceptions in that the error type (which could also be an actual <code>Exception</code> or a <code>Union</code> type) is part of the function signature.</p>
```python
from result import Result, Ok, Err, UnwrapError
from dataclasses import dataclass
@dataclass
class ComputationError:
number: int
def compute(number: int) -> Result[int, …
```

Include `Result` in `UnwrapError`

---

CHANGELOG.md

Might've just forgotten to drop the 'rc` prefix during last release

Fix changelog release version references for 0.6.0-rc.1

---

CHANGELOG.md
result/result.py
tests/type-checking/test_result.yml

Allow slightly more flexible typing, by letting `Ok` and `Err` be covariant.
A concrete example of when this is useful:
```py
from typing import Union
from result import Ok, Err
def test_union_err() -> None:
def union_err() -> Union[Err[str], Err[Exception]]:
return Err("hello")
ue: Err[Union[str, Exception]] = union_err()
def test_union_ok() -> None:
def union_ok() -> Union[Ok[str], Ok[int]]:
return Ok("hello")
uo: Ok[Union[str, int]] = union_ok()
```

Make Ok and Err covariant

---

pyproject.toml

To keep this library ‘mypy strict’, change the Mypy config to the
equivalent of --strict on the command line. (Config values were copied
from ‘mypy --help’ output into the config file.)
depends on these pull requests:

Make mypy run as --strict

---

pyproject.toml
result/result.py
tests/test_pattern_matching.py
tests/test_result.py

Changes:
- Adapt test_repr(): assert on actual expected values, add docstring,
drop obsolete u'foo' python 2 syntax
- Adapt pattern matching tests to not have any dead code; add docstring
- Add coverage excludes for typing.overloads() function bodies that are
never executed
- Tell pytest --cov to cover the result/ and tests/ dir, not arbitrary
Python code in the root dir (such as setup.py)
The result is 100% test coverage: 🎉
Name                             Stmts   Miss  Cover
----------------------------------------------------
result/__init__.py                   3      0   100%
result/result.py                   106      0   100%
tests/test_pattern_matching.py      15      0   100%
tests/test_result.py               134      0   100%
---------------------------------------------------- …

Adapt a few tests to reach 100% code coverage in tests

---

CHANGELOG.md

I'm going to update releasing doc to mention updating links in another PR

Update changelog diff link for 0.7.0

---

README.rst
result/result.py
tests/test_result.py

See #74 . `Result[T, E].unwrap_or_else(func_E_to_T)` always returns a "T"/OK type by forcing E -> T "the error back to the ok type" with a function/callback.

Implement Ok.unwrap_or_else and Err.unwrap_or_else

---

src/result/result.py
tests/test_pattern_matching.py
tests/test_result.py

Since we're py37+ only now, add `from __future__ import annotations` and
use PEP 563 style postponed annotation evaluation everywhere; see
https://www.python.org/dev/peps/pep-0563/
In practice this means stringified annotations are no longer needed.
Closes #70.

Adopt PEP 563 postponed annotation evaluation

---

CHANGELOG.md
README.rst
setup.cfg
src/result/__init__.py
src/result/result.py
tests/test_result.py

Add decorator to turn regular functions in Result returning ones
Add a as_result() helper to make a decorator to turn a function into one
that returns a Result: Regular return values are turned into
Ok(return_value). Raised exceptions of the specified exception type(s)
are turned into Err(exc).
The decorator is signature-preserving, except for wrapping the return
type into a Result, of course.
For type annotations, this depends on typing.ParamSpec which requires
Python 3.10+ (or use typing_extensions); see
PEP612 (https://www.python.org/dev/peps/pep-0612/).
Fixes #33.

Add decorator to turn regular functions in Result returning ones

---

tests/type-checking/test_result.yml

This has changed in newer mypy versions.
Fixes #94.

Remove * from expected mypy output

---

requirements-dev.txt

Just use the latest available (and compatible) versions for local development and CI.
Without a proper upgrading process in place, which is overkill for a small project like this, we should just deal with fallout whenever it happens instead of slowly getting stuck in the past… and missing issues occurring with newer tools as they become available.
For example, an older pytest version (6.x) was used, while 7.x is out for a while already. Same for other tools like twine. Latest version as of 2022-09-16:
$ pip freeze | grep --fixed-strings --file=requirements-dev.txt
build==0.8.0
flake8==5.0.4
mypy==0.971
mypy-extensions==0.4.3
pytest==7.1.3
pytest-cov==3.0.0
pytest-mypy-plugins==1.10.0
twine==4.0.1

No longer pin development dependencies

---

src/result/__init__.py

I noticed while doing,
```
pip install git+https://github.com/rustedpy/result
```
The unreleased master branch version is reported as `0.8.0`, which is wrong. We can set to to `0.0.0` until we need to make a release so people aren't confused if they're installing the master branch version

Change unrelease version to "0.9.0.dev0"

---

.github/workflows/ci.yml
CHANGELOG.md
pyproject.toml
setup.cfg
tests/type-checking/test_result.yml
tox.ini

Now that Python 3.11 is released, it is time to start officially supporting it.

Add support for Python 3.11

---

CHANGELOG.md
src/result/result.py
tests/type-checking/test_result.yml

This PR addresses a number of type inference related issues I've encountered with the result library.
Issue 1: Return types of methods are overly broad.
This leads to having to do casting or other trickery when you are working with an object that is known to be either `Ok` or `Err`, which is usually the case after having done an `isinstance` check. This PR narrows return types as much as possible, resolving this issue. The improvement is illustrated by an added test: `map_ok_err`.
Issue 2: Method parameter types reference type variables that cannot be inferred.
This leads to problems with type inference when calling methods on objects that are merely bounded to the `Result` union type. This PR addresses this by broadening types for unused method arguments to `object`. As a result, methods …

Type annotation cleanup

---

README.rst

The build badge at the top of the README became unavailable/broken due to https://github.com/badges/shields/issues/8671.
I also changed the link target to a more direct, workflow file-based URL to show the CI workflows for the `master` branch.

Fix build badge

---

CHANGELOG.md
MIGRATING.md
src/result/result.py
tests/test_result.py
tests/type-checking/test_result.yml

Closes #119
Force callers to specify an initial value.
`fp-ts` in the TypeScript world have an `Either` type, which requires explicit values, even if it's `undefined` or `null` (equivalent to Python's `None`). I think we can do the same here.

fix: remove overloaded '__init__' methods on 'Ok'

---

CHANGELOG.md
src/result/result.py
tests/test_result.py

Closes #37
`.value` to be removed in a future version
TODO: Create a GitHub issue to not forget this for next release

Add `.ok_value` and `.err_value`, deprecate `.value`

---

.github/workflows/ci.yml
CHANGELOG.md
setup.cfg
src/result/result.py
tox.ini

Python 3.7 reached end-of-life a few days ago, so it's time to drop support for it.
This doesn't result in significant upgrade potential to the code base; it only makes us slightly less dependent on `typing_extensions`.

Drop support for Python 3.7

---

src/result/result.py

The 'value' property is deprecated and instead 'ok_value' and 'err_value' must be used for 'Ok' and 'Err'. Due to the value for `__match_args__` not being updated, the deprecation warning was being raised when the user is using the `match` statement.
This fixes #127.

Fix the match args to use the correct attributes

---

src/result/result.py

Looking at well-typed code bases like FastAPI and Starlette, there doesn't seem to be any precedent for declaring the field separately outside the `__init__` method params. So this PR removes the `_value: T` field declaration in the `Ok` class. The `Err` class already didn't have it

Remove the `_value: T` declaration from the Ok class

---

RELEASING.md

"It is recommended to no longer upload signatures to PyPI."

Remove gpg signing step from releasing doc

---

CHANGELOG.md
src/result/result.py
tests/test_result.py

Continuation of https://github.com/rustedpy/result/pull/100
Fixes https://github.com/rustedpy/result/issues/98
Makes the captured `Err` value visible in the error message when `expect` or `unwrap` is called

Improve `unwrap`/`expect` error message

---

CHANGELOG.md
README.rst
src/result/__init__.py
src/result/result.py
tests/type-checking/test_result.yml

I'd say this is a more performant implementation than #72 as it doesn't use `is instance` checks at all.
Added tests, changelog & took a stab at main readme (although this is up to maintainers, whether this should be advertised as a better approach).
On my laptop one of the mypy tests is failing on 3.9, but that's not related to my change (complains about `|` where `Union` should be)
closes #69

Add `is_ok` and `is_err` typeguard functions

---

CHANGELOG.md
src/result/result.py
tests/test_result.py

Add async version of and_then combinator.
Tested with named functions only because AFAIK async lambdas don't exist.

and_then_async

---

README.rst

Fixes https://github.com/rustedpy/result/issues/141

Fix old README example, update docs to highlight `Result` always contains a value

---

README.rst

This Readme section shows how the code looks with the "elegant" `match` construct.
Part of its elegance is no need to create an intermediate variable—while preserving the clarity of the code.
So I made the `match` example more idiomatic. And IMO it demonstrates more strongly the benefit of this project.

Update README.rst—cleaned up match example

---

Makefile
README.md
docs/.pages
docs/README.md
docs/result.md
requirements-dev.txt

docs: Generate docs

---

README.md

Addresses issue highlighted in https://github.com/rustedpy/result/pull/155#discussion_r1414986865

docs: Update do-notation examples in README

---

docs/result.md
src/result/result.py

Fix issue: #169 
I think the best option is to use a little bit of markdown, but if u want to use pure pydoc strings, I can easily swap to ">>>" with keeping all the newlines.
Also sorry for not rendering docs, I don't use python often so I dunno how to make module usable in command line, and I don't wanna break your docs while using lazydocs API
Waiting for your respond
GNUSheep

Check all pydoc strings, fix problem with invalid rendered markdown

---

setup.cfg

Closes #171
See https://pypi.org/help/#description-content-type

fix: PyPI not showing description

---

README.md

Closes https://github.com/rustedpy/result/issues/174

docs: update readme to mention usage of isinstance to narrow types

---

CHANGELOG.md
docs/result.md
src/result/result.py
tests/test_result.py

Hello! In Rust 1.76 `inspect` and `inspect_err` methods were stabilized what are very handy when an error (or a value) must be logged. So I implemented them here.
Instead of doing this:
```python
def get_x_from_somewhere() -> Result[..., str]: ...
x = get_x_from_somewhere()
match x:
case Err(e):
logger.error("hello world %s", e)
y = x.and_then(upload_to_s3_bucket)
```
You can now do that:
```python
def get_x_from_somewhere() -> Result[..., str]: ...
y = get_x_from_somewhere().inspect_err(lambda e: logger.error("hello world %s", e)).and_then(upload_to_s3_bucket)
```

feat: add `.inspect()` and `.inspect_err()` methods

---

CHANGELOG.md
README.md
docs/README.md
docs/result.md
setup.cfg
src/result/result.py
tests/type_checking/test_result.yml

... to improve type narrowing for `is_ok` and `is_err` type guards.
Starting from Python 3.13 `TypeIs` is in the standards `typing` module. I decided to not introduce anything Python 3.13, since it should probably be handled in a seperate PR (see #181). 
See: https://github.com/rustedpy/result/issues/193

Replace TypeGuard with TypeIs
